export class PageConstant {
  static readonly PAGE_INDEX = '/pages/Index';
  static readonly PAGE_HOME = '/pages/HomePage';
  static readonly PAGE_CHAT = '/pages/ChatPage';
  static readonly PAGE_LOGIN = '/pages/LoginPage';
  static readonly PAGE_SETTING = '/pages/SettingPage';
  static readonly PAGE_ABOUT = '/pages/AboutPage';
  static readonly PAGE_MODEL_LIST = '/pages/ModelListPage';
  static readonly PAGE_MODEL_ADD_EDIT = '/pages/ModelAddAndEditPage';
}